# Generated by Django 4.0.2 on 2022-03-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomtipusu', models.CharField(max_length=20)),
                ('esttipusu', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomusu', models.CharField(max_length=20)),
                ('conusu', models.CharField(max_length=30)),
                ('estusu', models.IntegerField()),
            ],
        ),
    ]
