# Generated by Django 4.0.3 on 2022-04-20 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notas', '0003_carrera_curso_distrito_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='curso',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipousuario',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nompro', models.CharField(max_length=50)),
                ('apepro', models.CharField(max_length=50)),
                ('dnipro', models.CharField(max_length=50)),
                ('direccionpro', models.CharField(max_length=50)),
                ('emailpro', models.EmailField(max_length=254)),
                ('estpro', models.IntegerField()),
                ('distritopro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notas.distrito')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notas.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nomadm', models.CharField(max_length=50)),
                ('apeadm', models.CharField(max_length=50)),
                ('dniadm', models.CharField(max_length=50)),
                ('direccionadm', models.CharField(max_length=50)),
                ('emailadm', models.EmailField(max_length=254)),
                ('estadm', models.IntegerField()),
                ('distritoadm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notas.distrito')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notas.usuario')),
            ],
        ),
    ]
