# Generated by Django 4.0.2 on 2022-04-24 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notas', '0004_alter_carrera_id_alter_curso_id_alter_distrito_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipousu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notas.tipousuario'),
        ),
    ]
