# Generated by Django 4.0.2 on 2022-04-27 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notas', '0006_remove_usuario_tipousu_estudiante_tipousu'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativo',
            name='tipousu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notas.tipousuario'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='tipousu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notas.tipousuario'),
        ),
    ]
