# Generated by Django 4.0.2 on 2022-04-27 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notas', '0007_administrativo_tipousu_profesor_tipousu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrativo',
            name='tipousu',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='tipousu',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='tipousu',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipousu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notas.tipousuario'),
        ),
    ]
