# Generated by Django 4.0.2 on 2022-04-28 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notas', '0008_remove_administrativo_tipousu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tittar', models.CharField(max_length=1000)),
                ('destar', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tittar', models.CharField(max_length=1000)),
                ('destar', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea3',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tittar', models.CharField(max_length=1000)),
                ('destar', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea4',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tittar', models.CharField(max_length=1000)),
                ('destar', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea5',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tittar', models.CharField(max_length=1000)),
                ('destar', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sesion1_nt', models.IntegerField()),
                ('sesion1_asis', models.CharField(max_length=50)),
                ('soltarea1', models.CharField(max_length=1000)),
                ('notatarea1', models.IntegerField()),
                ('sesion2_nt', models.IntegerField()),
                ('sesion2_asis', models.CharField(max_length=50)),
                ('soltarea2', models.CharField(max_length=1000)),
                ('notatarea2', models.IntegerField()),
                ('sesion3_nt', models.IntegerField()),
                ('sesion3_asis', models.CharField(max_length=50)),
                ('soltarea3', models.CharField(max_length=1000)),
                ('notatarea3', models.IntegerField()),
                ('sesion4_nt', models.IntegerField()),
                ('sesion4_asis', models.CharField(max_length=50)),
                ('soltarea4', models.CharField(max_length=1000)),
                ('notatarea4', models.IntegerField()),
                ('sesion5_nt', models.IntegerField()),
                ('sesion5_asis', models.CharField(max_length=50)),
                ('soltarea5', models.CharField(max_length=1000)),
                ('notatarea5', models.IntegerField()),
                ('alumno', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notas.estudiante')),
                ('curso', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notas.curso')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notas.profesor')),
                ('tarea1_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notas.tarea1')),
                ('tarea2_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notas.tarea2')),
                ('tarea3_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notas.tarea3')),
                ('tarea4_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notas.tarea4')),
                ('tarea5_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notas.tarea5')),
            ],
        ),
    ]
