# Generated by Django 4.0.2 on 2022-04-28 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notas', '0009_tarea1_tarea2_tarea3_tarea4_tarea5_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea1',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notas.carrera'),
        ),
        migrations.AddField(
            model_name='tarea1',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notas.curso'),
        ),
        migrations.AddField(
            model_name='tarea1',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notas.profesor'),
        ),
        migrations.AddField(
            model_name='tarea2',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notas.carrera'),
        ),
        migrations.AddField(
            model_name='tarea2',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notas.curso'),
        ),
        migrations.AddField(
            model_name='tarea2',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notas.profesor'),
        ),
        migrations.AddField(
            model_name='tarea3',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notas.carrera'),
        ),
        migrations.AddField(
            model_name='tarea3',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notas.curso'),
        ),
        migrations.AddField(
            model_name='tarea3',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notas.profesor'),
        ),
        migrations.AddField(
            model_name='tarea4',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notas.carrera'),
        ),
        migrations.AddField(
            model_name='tarea4',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notas.curso'),
        ),
        migrations.AddField(
            model_name='tarea4',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notas.profesor'),
        ),
        migrations.AddField(
            model_name='tarea5',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notas.carrera'),
        ),
        migrations.AddField(
            model_name='tarea5',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notas.curso'),
        ),
        migrations.AddField(
            model_name='tarea5',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notas.profesor'),
        ),
    ]
