# Generated by Django 4.0.2 on 2022-04-28 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notas', '0010_tarea1_carrera_tarea1_curso_tarea1_profesor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notas.curso'),
        ),
    ]
